# Generated by Django 5.2.14 on 2026-05-26 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('playing', 'Playing'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], default='lobby', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_round_idx', models.PositiveIntegerField(default=0)),
                ('current_question_idx', models.PositiveIntegerField(default=0)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='SessionPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('player', 'Player'), ('spectator', 'Spectator')], default='player', max_length=16)),
                ('is_host', models.BooleanField(default=False)),
                ('guest_token_hash', models.CharField(blank=True, max_length=128)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game_sessions.session')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_score', models.FloatField(default=0)),
                ('normalized_score', models.FloatField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='quizzes.round')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='game_sessions.session')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='game_sessions.sessionplayer')),
            ],
        ),
        migrations.CreateModel(
            name='AntiCheatEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('soft', 'Soft'), ('hard', 'Hard')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anticheat_events', to='quizzes.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticheat_events', to='game_sessions.session')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticheat_events', to='game_sessions.sessionplayer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_text', models.TextField(blank=True)),
                ('submitted_payload', models.JSONField(blank=True, default=dict)),
                ('accepted', models.BooleanField(default=False)),
                ('points_awarded', models.FloatField(default=0)),
                ('judge_mode_used', models.CharField(blank=True, max_length=16)),
                ('judge_latency_ms', models.PositiveIntegerField(default=0)),
                ('judge_metadata', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_submissions', to='quizzes.question')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_submissions', to='quizzes.round')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_submissions', to='game_sessions.session')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_submissions', to='game_sessions.sessionplayer')),
            ],
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['quiz', 'status'], name='game_sessio_quiz_id_47d6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status', '-created_at'], name='game_sessio_status_85044c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionplayer',
            index=models.Index(fields=['session', 'role'], name='game_sessio_session_dbe58b_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionplayer',
            index=models.Index(fields=['session', 'is_host'], name='game_sessio_session_35507c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roundresult',
            unique_together={('session', 'round', 'player')},
        ),
        migrations.AddIndex(
            model_name='anticheatevent',
            index=models.Index(fields=['session', 'player', 'kind'], name='game_sessio_session_f17b35_idx'),
        ),
        migrations.AddIndex(
            model_name='anticheatevent',
            index=models.Index(fields=['occurred_at'], name='game_sessio_occurre_0679f6_idx'),
        ),
        migrations.AddIndex(
            model_name='answersubmission',
            index=models.Index(fields=['session', 'round', 'player'], name='game_sessio_session_f4de6c_idx'),
        ),
        migrations.AddIndex(
            model_name='answersubmission',
            index=models.Index(fields=['question', 'player'], name='game_sessio_questio_65440e_idx'),
        ),
    ]
