# Generated by Django 5.2.14 on 2026-05-26 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('topic', models.CharField(blank=True, max_length=180)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=16)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=16)),
                ('anticheat_strictness', models.CharField(choices=[('strict', 'Strict'), ('friendly', 'Friendly'), ('off', 'Off')], default='friendly', max_length=16)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('meta_strategy', 'Meta-strategy'), ('list_race', 'List race'), ('buzz_in', 'Buzz-in'), ('sync_open', 'Synchronized open-answer')], max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='quizzes.quiz')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('quiz', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SourceMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('topic', 'Topic'), ('text', 'Text'), ('pdf', 'PDF'), ('url', 'URL')], max_length=16)),
                ('content', models.TextField()),
                ('original_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='source_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='quizzes.sourcematerial'),
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_normalized_score', models.FloatField(default=0)),
                ('plays_count', models.PositiveIntegerField(default=0)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='quizzes.quiz')),
            ],
            options={
                'indexes': [models.Index(fields=['quiz', '-best_normalized_score'], name='quizzes_lea_quiz_id_06c88f_idx')],
                'unique_together': {('quiz', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('prompt_blocks', models.JSONField(blank=True, default=list)),
                ('answer_widget', models.JSONField(blank=True, default=dict)),
                ('canonical_answer', models.TextField(blank=True)),
                ('acceptable_answers', models.JSONField(blank=True, default=list)),
                ('judge_mode', models.CharField(choices=[('fuzzy', 'Fuzzy'), ('llm', 'LLM')], default='fuzzy', max_length=16)),
                ('judge_config', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.round')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('round', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['visibility', '-updated_at'], name='quizzes_qui_visibil_ddddc8_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['topic'], name='quizzes_qui_topic_7203f1_idx'),
        ),
    ]
