# Generated by Codex on 2026-05-26

from django.db import migrations, models


def categorize_existing_quizzes(apps, _schema_editor):
    Quiz = apps.get_model("quizzes", "Quiz")
    category_keywords = {
        "science": [
            "science",
            "physics",
            "quantum",
            "chemistry",
            "biology",
            "math",
            "schrodinger",
            "equation",
        ],
        "tv": ["tv", "show", "movie", "film", "game of thrones", "got", "series"],
        "sports": ["sports", "baseball", "mlb", "stadium", "nba", "nfl", "soccer"],
        "geography": ["geography", "flag", "flags", "country", "countries", "capital", "map", "cameroon"],
        "history": ["history", "war", "empire", "ancient", "president", "revolution"],
    }
    for quiz in Quiz.objects.all():
        search_text = f"{quiz.title} {quiz.topic} {quiz.description}".lower()
        category = "general"
        for candidate, keywords in category_keywords.items():
            if any(keyword in search_text for keyword in keywords):
                category = candidate
                break
        quiz.category = category
        quiz.status = "draft" if _looks_like_draft(search_text) else "ready"
        quiz.save(update_fields=["category", "status"])


def _looks_like_draft(search_text):
    draft_markers = [
        "ai draft",
        "first-pass generated quiz draft",
        "review and refine before publishing",
    ]
    return any(marker in search_text for marker in draft_markers)


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="category",
            field=models.CharField(
                choices=[
                    ("science", "Science"),
                    ("tv", "TV & Movies"),
                    ("sports", "Sports"),
                    ("geography", "Geography"),
                    ("history", "History"),
                    ("general", "General"),
                ],
                default="general",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready", "Ready"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.RunPython(categorize_existing_quizzes, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(fields=["status", "-updated_at"], name="quizzes_qui_status_5d04cd_idx"),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(fields=["category", "-updated_at"], name="quizzes_qui_categor_5032e2_idx"),
        ),
    ]
