# Generated by Codex on 2026-05-26

from django.db import migrations


def mark_legacy_drafts(apps, _schema_editor):
    Quiz = apps.get_model("quizzes", "Quiz")
    draft_markers = [
        "ai draft",
        "first-pass generated quiz draft",
        "review and refine before publishing",
    ]
    for quiz in Quiz.objects.all():
        search_text = f"{quiz.title} {quiz.description}".lower()
        if any(marker in search_text for marker in draft_markers):
            quiz.status = "draft"
            quiz.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_quiz_category_status"),
    ]

    operations = [
        migrations.RunPython(mark_legacy_drafts, migrations.RunPython.noop),
    ]
